# Generated by Django 4.2.30 on 2026-07-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('charts', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analyzer.dataset')),
            ],
        ),
    ]
